plugin 'slather'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'FrameAccessor' do
  pod 'FrameAccessorSwift', :path => '..'

  target 'FrameAccessorTests' do
      inherit! :search_paths
  end
end
